[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"
    X-Content-Type-Options = "nosniff"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
